name: Setup Go environment
 
on:
  push:
    branches: [main]
    
  pull_request: 
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-16.04
    name: build
    steps:
      - name: Check automation
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '1.15'
      - name: Check Go ver
        run: |
            go version
            ls
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '14'
      - run: npm install
      - run: npm test 
      - name: Install dependencies
        run: |
            go get github.com/franela/goblin
      - if: ${{success()}}
        name: Test dependency goblin
        run: |
            go test -v -cover
            ls
