name: Setup Go environment
 
on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-16.04
    name: build
    steps:
      - name: Check automation
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: '1.15'
      - name: Check Go ver
        run: |
            go version
      - name: Install dependencies
      - if: ${{success}}
        name: Test dependency goblin
        run:
            go get github.com/franela/goblin
